# Generated by Django 3.2.3 on 2021-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
    ]
